# Configuração do Hibernate
quarkus.datasource.db-kind=postgresql
%dev.quarkus.hibernate-orm.database.generation=validate
%dev,test.quarkus.hibernate-orm.log.bind-parameters=true
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.datasource.dev-ui.allow-sql=true

# Flyway Configuration
quarkus.flyway.locations=db/migration
quarkus.flyway.migrate-at-start=true
quarkus.flyway.clean-disabled=true
quarkus.flyway.validate-on-migrate=true
quarkus.flyway.out-of-order=false
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=0
%dev.quarkus.flyway.clean-at-start=true
%dev.quarkus.flyway.clean-disabled=false

# Image storage configuration
image.storage.path=/tmp/contraponto-images
image.base.url=http://localhost:8080

#################################
## OpenAPI                     ##
#################################
quarkus.smallrye-openapi.path=/openapi.yaml
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.footer=&#169; 2026 Contraponto - https://vepo.dev
quarkus.swagger-ui.path=/openapi
quarkus.swagger-ui.title=Contraponto - API