///usr/bin/env jbang "$0" "$@" ; exit $?
//JAVA 21+

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * Scans Java sources for modernization opportunities (Java 21+ idioms).
 * Run: jbang scripts/audit-java-idioms.java
 * Output: reports/java-idioms-audit.md
 */
class AuditJavaIdioms {

    private static final Pattern IS_PRESENT = Pattern.compile("\\.isPresent\\(\\)");
    private static final Pattern GET_AFTER_PRESENT = Pattern.compile("isPresent\\(\\)[\\s\\S]{0,120}?\\.get\\(\\)");
    private static final Pattern OLD_INSTANCEOF = Pattern.compile("instanceof\\s+[A-Z][\\w.$]*(\\s+\\w+)?\\s*\\)");
    private static final Pattern STRING_PLUS = Pattern.compile("\"[^\"]*\"\\s*\\+");
    private static final Pattern RECORD = Pattern.compile("\\b(record|public record)\\b");
    private static final Pattern ENTITY = Pattern.compile("@Entity");
    private static final Pattern FORM_PARAM = Pattern.compile("@FormParam");
    private static final Pattern APPLICATION_SCOPED = Pattern.compile("@ApplicationScoped|@RequestScoped");

    public static void main(String[] args) throws IOException {
        var root = Path.of(System.getProperty("user.dir"));
        var report = root.resolve("reports/java-idioms-audit.md");
        Files.createDirectories(report.getParent());

        Map<String, List<String>> findings = new LinkedHashMap<>();
        findings.put("optional_isPresent", new ArrayList<>());
        findings.put("optional_isPresent_get", new ArrayList<>());
        findings.put("instanceof_unbound", new ArrayList<>());
        findings.put("string_plus_concat", new ArrayList<>());
        findings.put("string_builder", new ArrayList<>());
        findings.put("record_candidates", new ArrayList<>());

        try (Stream<Path> paths = Files.walk(root.resolve("src"))) {
            paths.filter(p -> p.toString().endsWith(".java")).forEach(path -> scan(path, root, findings));
        }

        var sb = new StringBuilder();
        sb.append("# Java idioms audit\n\n");
        sb.append("Generated by `scripts/audit-java-idioms.java`. Re-run after modernization passes.\n\n");
        int total = 0;
        for (var entry : findings.entrySet()) {
            sb.append("## ").append(entry.getKey()).append(" (").append(entry.getValue().size()).append(")\n\n");
            if (entry.getValue().isEmpty()) {
                sb.append("_None._\n\n");
            } else {
                for (String line : entry.getValue()) {
                    sb.append("- ").append(line).append("\n");
                }
                sb.append("\n");
            }
            total += entry.getValue().size();
        }
        sb.append("## Summary\n\nTotal findings: **").append(total).append("**\n");
        Files.writeString(report, sb);
        System.out.println("Wrote " + report + " (" + total + " findings)");
    }

    private static void scan(Path path, Path root, Map<String, List<String>> findings) {
        String rel;
        try {
            rel = root.relativize(path).toString().replace('\\', '/');
            var content = Files.readString(path);
            var lines = content.split("\n");

            if (IS_PRESENT.matcher(content).find()) {
                for (int i = 0; i < lines.length; i++) {
                    if (lines[i].contains(".isPresent()")) {
                        findings.get("optional_isPresent").add(rel + ":" + (i + 1));
                    }
                }
            }
            if (GET_AFTER_PRESENT.matcher(content).find()) {
                findings.get("optional_isPresent_get").add(rel);
            }
            for (int i = 0; i < lines.length; i++) {
                var line = lines[i];
                if (line.contains("instanceof") && OLD_INSTANCEOF.matcher(line).find()
                        && !line.contains("instanceof WebApplicationException webEx")
                        && !line.matches(".*instanceof\\s+\\w+\\s+\\w+.*")) {
                    if (line.contains("instanceof") && !line.matches(".*instanceof [A-Za-z0-9_.$]+ [a-z][a-zA-Z0-9_]*.*")) {
                        findings.get("instanceof_unbound").add(rel + ":" + (i + 1));
                    }
                }
                if (STRING_PLUS.matcher(line).find() && !line.trim().startsWith("//")) {
                    findings.get("string_plus_concat").add(rel + ":" + (i + 1));
                }
                if (line.contains("new StringBuilder") && !content.contains("for (")) {
                    findings.get("string_builder").add(rel + ":" + (i + 1));
                }
            }
            if (!RECORD.matcher(content).find()
                    && content.contains("private final")
                    && !ENTITY.matcher(content).find()
                    && !FORM_PARAM.matcher(content).find()
                    && !APPLICATION_SCOPED.matcher(content).find()
                    && content.contains("public class")
                    && !content.contains("extends ")
                    && content.contains("get")
                    && path.toString().contains("/main/")) {
                if (content.matches("(?s).*(View|Row|Payload|Entry|Draft|Result|Data|Copy|Anchor|Metric|Series|Response)\\s*\\{.*")) {
                    findings.get("record_candidates").add(rel);
                }
            }
        } catch (IOException ignored) {
            // skip unreadable
        }
    }
}
