# Configurações do Cache Caffeine
quarkus.cache.caffeine.rendered-pages.initial-capacity=1000
quarkus.cache.caffeine.rendered-pages.maximum-size=10000
# Tempo para expirar após a última escrita (ex: 1 hora para posts)
quarkus.cache.caffeine.rendered-pages.expire-after-write=1H
# Ou expire-after-access para páginas menos importantes
# quarkus.cache.caffeine.other-pages.expire-after-access=30M

# Configurações HTTP para arquivos estáticos
quarkus.http.static-resources.cache.max-age=1Y
quarkus.http.static-resources.cache.immutable=true

# (Opcional) Se usar CDN ou proxy reverso, defina cabeçalhos padrão
# quarkus.http.header."Cache-Control".value=max-age=0, must-revalidate
# quarkus.http.header."Cache-Control".paths=/api/private/*