CREATE TABLE tb_message_threads (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR(200) NOT NULL,
    initiator_user_id   BIGINT NOT NULL,
    recipient_user_id   BIGINT NOT NULL,
    status              VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    created_at          TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    closed_at           TIMESTAMP(6),

    CONSTRAINT fk_message_threads_initiator FOREIGN KEY (initiator_user_id) REFERENCES tb_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_message_threads_recipient FOREIGN KEY (recipient_user_id) REFERENCES tb_users(id) ON DELETE CASCADE,
    CONSTRAINT chk_message_threads_status CHECK (status IN ('OPEN', 'CLOSED', 'FROZEN'))
);

CREATE INDEX idx_message_threads_initiator_created ON tb_message_threads(initiator_user_id, created_at DESC);
CREATE INDEX idx_message_threads_recipient_created ON tb_message_threads(recipient_user_id, created_at DESC);
CREATE INDEX idx_message_threads_status ON tb_message_threads(status);

CREATE TABLE tb_thread_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id       BIGINT NOT NULL,
    author_user_id  BIGINT NOT NULL,
    body            VARCHAR(2000) NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_thread_messages_thread FOREIGN KEY (thread_id) REFERENCES tb_message_threads(id) ON DELETE CASCADE,
    CONSTRAINT fk_thread_messages_author FOREIGN KEY (author_user_id) REFERENCES tb_users(id) ON DELETE CASCADE
);

CREATE INDEX idx_thread_messages_thread_created ON tb_thread_messages(thread_id, created_at);

CREATE TABLE tb_message_thread_participants (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id               BIGINT NOT NULL,
    user_id                 BIGINT NOT NULL,
    last_read_at            TIMESTAMP(6),
    last_read_message_id    BIGINT,

    CONSTRAINT fk_message_thread_participants_thread FOREIGN KEY (thread_id) REFERENCES tb_message_threads(id) ON DELETE CASCADE,
    CONSTRAINT fk_message_thread_participants_user FOREIGN KEY (user_id) REFERENCES tb_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_message_thread_participants_last_message FOREIGN KEY (last_read_message_id) REFERENCES tb_thread_messages(id) ON DELETE SET NULL,
    CONSTRAINT uq_message_thread_participants UNIQUE (thread_id, user_id)
);

CREATE INDEX idx_message_thread_participants_user ON tb_message_thread_participants(user_id);

CREATE TABLE tb_user_blocks (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_user_id     BIGINT NOT NULL,
    blocked_user_id     BIGINT NOT NULL,
    created_at          TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_user_blocks_blocker FOREIGN KEY (blocker_user_id) REFERENCES tb_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_blocks_blocked FOREIGN KEY (blocked_user_id) REFERENCES tb_users(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_blocks UNIQUE (blocker_user_id, blocked_user_id),
    CONSTRAINT chk_user_blocks_not_self CHECK (blocker_user_id <> blocked_user_id)
);

CREATE INDEX idx_user_blocks_blocker ON tb_user_blocks(blocker_user_id);

CREATE TABLE tb_message_reports (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id               BIGINT NOT NULL,
    reporter_user_id        BIGINT NOT NULL,
    status                  VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    created_at              TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    reviewed_at             TIMESTAMP(6),
    reviewed_by_user_id     BIGINT,

    CONSTRAINT fk_message_reports_thread FOREIGN KEY (thread_id) REFERENCES tb_message_threads(id) ON DELETE CASCADE,
    CONSTRAINT fk_message_reports_reporter FOREIGN KEY (reporter_user_id) REFERENCES tb_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_message_reports_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES tb_users(id) ON DELETE SET NULL,
    CONSTRAINT uq_message_reports_thread_reporter UNIQUE (thread_id, reporter_user_id),
    CONSTRAINT chk_message_reports_status CHECK (status IN ('PENDING', 'DISMISSED', 'REVIEWED'))
);

CREATE INDEX idx_message_reports_status_created ON tb_message_reports(status, created_at DESC);

ALTER TABLE tb_notifications
    ALTER COLUMN blog_id DROP NOT NULL;

ALTER TABLE tb_notifications
    ADD COLUMN message_thread_id BIGINT;

ALTER TABLE tb_notifications
    ADD CONSTRAINT fk_notifications_message_thread FOREIGN KEY (message_thread_id) REFERENCES tb_message_threads(id) ON DELETE CASCADE;

CREATE INDEX idx_notifications_message_thread ON tb_notifications(message_thread_id);
