CREATE TABLE tb_posts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug              VARCHAR(255) NOT NULL UNIQUE,
    author            VARCHAR(255) NOT NULL,
    title             VARCHAR(255),
    cover             OID,
    description       VARCHAR(512) NOT NULL,
    content           TEXT NOT NULL,
    published         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP(6) NOT NULL,
    published_at      TIMESTAMP(6),
    updated_at        TIMESTAMP(6) NOT NULL
);