ALTER TABLE tb_blogs
    ADD COLUMN IF NOT EXISTS git_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE tb_blogs
    ADD COLUMN IF NOT EXISTS git_remote_url VARCHAR(2048);

ALTER TABLE tb_blogs
    ADD COLUMN IF NOT EXISTS git_branch VARCHAR(255) NOT NULL DEFAULT 'main';

ALTER TABLE tb_blogs
    ADD COLUMN IF NOT EXISTS git_last_known_commit VARCHAR(64);
