ALTER TABLE tb_images ADD COLUMN blog_id BIGINT;
ALTER TABLE tb_images ADD COLUMN alt_text VARCHAR(512);
ALTER TABLE tb_images ADD COLUMN uploaded_by_user_id BIGINT;

CREATE TABLE tb_post_image_dependencies (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id  BIGINT NOT NULL,
    image_id BIGINT NOT NULL,
    role     VARCHAR(20) NOT NULL,
    CONSTRAINT fk_post_image_dep_post FOREIGN KEY (post_id) REFERENCES tb_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_image_dep_image FOREIGN KEY (image_id) REFERENCES tb_images(id) ON DELETE CASCADE,
    CONSTRAINT uq_post_image_dep UNIQUE (post_id, image_id, role)
);

CREATE INDEX idx_post_image_dep_image ON tb_post_image_dependencies(image_id);

CREATE TABLE tb_post_publication_image_dependencies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id  BIGINT NOT NULL,
    image_id        BIGINT NOT NULL,
    role            VARCHAR(20) NOT NULL,
    CONSTRAINT fk_pub_image_dep_pub FOREIGN KEY (publication_id) REFERENCES tb_post_publications(id) ON DELETE CASCADE,
    CONSTRAINT fk_pub_image_dep_image FOREIGN KEY (image_id) REFERENCES tb_images(id) ON DELETE CASCADE,
    CONSTRAINT uq_pub_image_dep UNIQUE (publication_id, image_id, role)
);

CREATE INDEX idx_pub_image_dep_image ON tb_post_publication_image_dependencies(image_id);

CREATE TABLE tb_custom_page_image_dependencies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custom_page_id  BIGINT NOT NULL,
    image_id        BIGINT NOT NULL,
    role            VARCHAR(20) NOT NULL,
    CONSTRAINT fk_page_image_dep_page FOREIGN KEY (custom_page_id) REFERENCES tb_custom_pages(id) ON DELETE CASCADE,
    CONSTRAINT fk_page_image_dep_image FOREIGN KEY (image_id) REFERENCES tb_images(id) ON DELETE CASCADE,
    CONSTRAINT uq_page_image_dep UNIQUE (custom_page_id, image_id, role)
);

CREATE INDEX idx_page_image_dep_image ON tb_custom_page_image_dependencies(image_id);

-- Backfill blog_id from post covers
UPDATE tb_images i
SET blog_id = (
    SELECT p.blog_id FROM tb_posts p WHERE p.cover_id = i.id LIMIT 1
)
WHERE blog_id IS NULL
  AND EXISTS (SELECT 1 FROM tb_posts p WHERE p.cover_id = i.id);

UPDATE tb_images i
SET blog_id = (
    SELECT p.blog_id
    FROM tb_post_publications pp
    JOIN tb_posts p ON p.id = pp.post_id
    WHERE pp.cover_id = i.id
    LIMIT 1
)
WHERE blog_id IS NULL
  AND EXISTS (
    SELECT 1 FROM tb_post_publications pp WHERE pp.cover_id = i.id
);

-- Remaining orphans: assign to first active main blog (dev seed / legacy data)
UPDATE tb_images i
SET blog_id = (SELECT b.id FROM tb_blogs b WHERE b.main = true AND b.active = true ORDER BY b.id LIMIT 1)
WHERE blog_id IS NULL;

ALTER TABLE tb_images ALTER COLUMN blog_id SET NOT NULL;
ALTER TABLE tb_images ADD CONSTRAINT fk_images_blog FOREIGN KEY (blog_id) REFERENCES tb_blogs(id);
ALTER TABLE tb_images ADD CONSTRAINT fk_images_uploaded_by FOREIGN KEY (uploaded_by_user_id) REFERENCES tb_users(id);

CREATE INDEX idx_images_blog ON tb_images(blog_id);
