CREATE TABLE tb_series (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blog_id    BIGINT NOT NULL,
    title      VARCHAR(255) NOT NULL,
    slug       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_series_blog FOREIGN KEY (blog_id) REFERENCES tb_blogs(id) ON DELETE CASCADE,
    CONSTRAINT uq_series_blog_slug UNIQUE (blog_id, slug)
);

CREATE INDEX idx_series_blog_id ON tb_series(blog_id);

ALTER TABLE tb_posts
    ADD COLUMN serie_id BIGINT;

ALTER TABLE tb_posts
    ADD CONSTRAINT fk_posts_serie FOREIGN KEY (serie_id) REFERENCES tb_series(id) ON DELETE SET NULL;
