ALTER TABLE tb_users ADD COLUMN pending_email VARCHAR(255) NULL;

CREATE TABLE tb_user_account_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    type       VARCHAR(30) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    new_email  VARCHAR(255),
    expires_at TIMESTAMP(6) NOT NULL,
    used_at    TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_user_account_tokens_user FOREIGN KEY (user_id) REFERENCES tb_users(id) ON DELETE CASCADE
);

CREATE INDEX idx_user_account_tokens_hash ON tb_user_account_tokens(token_hash);
CREATE INDEX idx_user_account_tokens_user_type ON tb_user_account_tokens(user_id, type);
