CREATE TABLE tb_account_email_outbox (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind           VARCHAR(40) NOT NULL,
    recipient      VARCHAR(255) NOT NULL,
    subject        VARCHAR(512) NOT NULL,
    payload        TEXT NOT NULL,
    attempt_count  INT NOT NULL DEFAULT 0,
    next_retry_at  TIMESTAMP(6) NOT NULL,
    created_at     TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_error     TEXT
);

CREATE INDEX idx_account_email_outbox_next_retry ON tb_account_email_outbox(next_retry_at, id);
