CREATE TABLE tb_git_sync_runs (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blog_id               BIGINT NOT NULL,
    post_id               BIGINT,
    operation             VARCHAR(16) NOT NULL,
    trigger_kind          VARCHAR(32) NOT NULL,
    started_at            TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    finished_at           TIMESTAMP(6),
    outcome               VARCHAR(16) NOT NULL,
    git_error_kind        VARCHAR(32) NOT NULL DEFAULT 'NONE',
    repository_readable   BOOLEAN NOT NULL DEFAULT FALSE,
    data_loadable         BOOLEAN NOT NULL DEFAULT FALSE,
    remote_url            VARCHAR(2048),
    branch                VARCHAR(255),
    commit_before         VARCHAR(64),
    commit_after          VARCHAR(64),
    convention_snapshot   TEXT,
    settings_snapshot     TEXT,
    summary_message       VARCHAR(512),
    error_detail          VARCHAR(4096),

    CONSTRAINT fk_git_sync_runs_blog FOREIGN KEY (blog_id) REFERENCES tb_blogs(id) ON DELETE CASCADE,
    CONSTRAINT fk_git_sync_runs_post FOREIGN KEY (post_id) REFERENCES tb_posts(id) ON DELETE SET NULL,
    CONSTRAINT chk_git_sync_runs_operation CHECK (operation IN ('EXPORT', 'IMPORT')),
    CONSTRAINT chk_git_sync_runs_outcome CHECK (outcome IN ('SUCCESS', 'PARTIAL', 'FAILED', 'SKIPPED'))
);

CREATE INDEX idx_git_sync_runs_blog_started ON tb_git_sync_runs(blog_id, started_at DESC);

CREATE TABLE tb_git_sync_run_entries (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id            BIGINT NOT NULL,
    sequence          INT NOT NULL,
    phase             VARCHAR(32) NOT NULL,
    level             VARCHAR(8) NOT NULL,
    post_id           BIGINT,
    markdown_path     VARCHAR(1024),
    outcome           VARCHAR(16) NOT NULL,
    message           VARCHAR(1024) NOT NULL,
    remediation       VARCHAR(2048),
    technical_detail  VARCHAR(4096),

    CONSTRAINT fk_git_sync_run_entries_run FOREIGN KEY (run_id) REFERENCES tb_git_sync_runs(id) ON DELETE CASCADE,
    CONSTRAINT fk_git_sync_run_entries_post FOREIGN KEY (post_id) REFERENCES tb_posts(id) ON DELETE SET NULL,
    CONSTRAINT chk_git_sync_run_entries_level CHECK (level IN ('INFO', 'WARN', 'ERROR')),
    CONSTRAINT chk_git_sync_run_entries_outcome CHECK (outcome IN ('SUCCESS', 'SKIPPED', 'FAILED'))
);

CREATE INDEX idx_git_sync_run_entries_run_seq ON tb_git_sync_run_entries(run_id, sequence);

ALTER TABLE tb_notifications ADD COLUMN git_sync_run_id BIGINT;
ALTER TABLE tb_notifications ADD CONSTRAINT fk_notifications_git_sync_run
    FOREIGN KEY (git_sync_run_id) REFERENCES tb_git_sync_runs(id) ON DELETE CASCADE;
