CREATE TABLE tb_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(15) NOT NULL UNIQUE,
    email         VARCHAR(255) NOT NULL UNIQUE,
    name          VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP(6) NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_users_email    ON tb_users(email);
CREATE INDEX idx_users_username ON tb_users(username);

INSERT INTO tb_users (username, email, name, password_hash, active) VALUES 
                     ('admin', 'admin@contraponto.blog', 'Administrator', '$2a$10$9JdzFX8ar0ZcKP5bQkduBuwhFBRBgMW7.pCV4btIDcPgf.zdDGcCO', TRUE);

CREATE TABLE tb_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE,
    filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size BIGINT NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    url VARCHAR(500) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_images_uuid ON tb_images(uuid);
CREATE INDEX idx_images_active ON tb_images(active);
CREATE INDEX idx_images_created_at ON tb_images(created_at);

CREATE TABLE tb_posts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug              VARCHAR(255) NOT NULL UNIQUE,
    author            VARCHAR(255) NOT NULL,
    title             VARCHAR(255),
    cover_id          BIGINT,
    description       VARCHAR(512) NOT NULL,
    content           TEXT NOT NULL,
    published         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP(6) NOT NULL,
    published_at      TIMESTAMP(6),
    updated_at        TIMESTAMP(6) NOT NULL,

    CONSTRAINT fk_posts_cover_image FOREIGN KEY (cover_id) REFERENCES tb_images(id)
);