CREATE TABLE tb_post_slug_aliases (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT NOT NULL,
    blog_id     BIGINT NOT NULL,
    slug        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_post_slug_aliases_post FOREIGN KEY (post_id) REFERENCES tb_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_slug_aliases_blog FOREIGN KEY (blog_id) REFERENCES tb_blogs(id) ON DELETE CASCADE,
    CONSTRAINT uk_post_slug_aliases_blog_slug UNIQUE (blog_id, slug)
);

INSERT INTO tb_post_slug_aliases (post_id, blog_id, slug, created_at)
SELECT DISTINCT p.id, p.blog_id, pub.slug, NOW()
FROM tb_post_publications pub
JOIN tb_posts p ON p.id = pub.post_id
WHERE pub.slug <> p.slug
ON CONFLICT (blog_id, slug) DO NOTHING;
