CREATE TABLE tb_post_publications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id         BIGINT NOT NULL,
    version         INT NOT NULL,
    published_at    TIMESTAMP(6) NOT NULL,
    slug            VARCHAR(255) NOT NULL,
    title           VARCHAR(255),
    description     VARCHAR(512) NOT NULL,
    content         TEXT NOT NULL,
    format          VARCHAR(20) NOT NULL,
    cover_id        BIGINT,

    CONSTRAINT fk_post_publications_post FOREIGN KEY (post_id) REFERENCES tb_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_publications_cover FOREIGN KEY (cover_id) REFERENCES tb_images(id),
    CONSTRAINT uq_post_publications_post_version UNIQUE (post_id, version)
);

CREATE INDEX idx_post_publications_post_id ON tb_post_publications(post_id);

CREATE TABLE tb_post_publication_tags (
    publication_id BIGINT NOT NULL,
    tag_id         BIGINT NOT NULL,

    CONSTRAINT pk_post_publication_tags PRIMARY KEY (publication_id, tag_id),
    CONSTRAINT fk_post_publication_tags_publication FOREIGN KEY (publication_id) REFERENCES tb_post_publications(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_publication_tags_tag FOREIGN KEY (tag_id) REFERENCES tb_tags(id) ON DELETE CASCADE
);

CREATE INDEX idx_post_publication_tags_tag_id ON tb_post_publication_tags(tag_id);

ALTER TABLE tb_posts ADD COLUMN live_publication_id BIGINT;

-- Backfill version 1 for every already-published post
INSERT INTO tb_post_publications (post_id, version, published_at, slug, title, description, content, format, cover_id)
SELECT p.id,
       1,
       COALESCE(p.published_at, p.updated_at, p.created_at),
       p.slug,
       p.title,
       p.description,
       p.content,
       p.format,
       p.cover_id
FROM tb_posts p
WHERE p.published = TRUE;

INSERT INTO tb_post_publication_tags (publication_id, tag_id)
SELECT pub.id, pt.tag_id
FROM tb_post_publications pub
JOIN tb_post_tags pt ON pt.post_id = pub.post_id
WHERE pub.version = 1;

UPDATE tb_posts p
SET live_publication_id = pub.id
FROM tb_post_publications pub
WHERE pub.post_id = p.id
  AND pub.version = 1
  AND p.published = TRUE;

ALTER TABLE tb_posts
    ADD CONSTRAINT fk_posts_live_publication FOREIGN KEY (live_publication_id) REFERENCES tb_post_publications(id);
