CREATE TABLE tb_blog_audience (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    blog_id          BIGINT NOT NULL,
    followed         BOOLEAN NOT NULL DEFAULT FALSE,
    email_subscribed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_blog_audience_user FOREIGN KEY (user_id) REFERENCES tb_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_blog_audience_blog FOREIGN KEY (blog_id) REFERENCES tb_blogs(id) ON DELETE CASCADE,
    CONSTRAINT uq_blog_audience_user_blog UNIQUE (user_id, blog_id),
    CONSTRAINT chk_blog_audience_active CHECK (followed OR email_subscribed)
);

CREATE INDEX idx_blog_audience_blog_followed ON tb_blog_audience(blog_id) WHERE followed = TRUE;
CREATE INDEX idx_blog_audience_blog_email ON tb_blog_audience(blog_id) WHERE email_subscribed = TRUE;

CREATE TABLE tb_notifications (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id  BIGINT NOT NULL,
    type               VARCHAR(32) NOT NULL,
    blog_id            BIGINT NOT NULL,
    post_id            BIGINT,
    publication_id     BIGINT,
    actor_user_id      BIGINT,
    read               BOOLEAN NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_user_id) REFERENCES tb_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_blog FOREIGN KEY (blog_id) REFERENCES tb_blogs(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_post FOREIGN KEY (post_id) REFERENCES tb_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_publication FOREIGN KEY (publication_id) REFERENCES tb_post_publications(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_actor FOREIGN KEY (actor_user_id) REFERENCES tb_users(id) ON DELETE SET NULL
);

CREATE INDEX idx_notifications_recipient_read_created ON tb_notifications(recipient_user_id, read, created_at DESC);

CREATE TABLE tb_email_notification_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id  BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    sent_at         TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_email_notification_log_publication FOREIGN KEY (publication_id) REFERENCES tb_post_publications(id) ON DELETE CASCADE,
    CONSTRAINT fk_email_notification_log_user FOREIGN KEY (user_id) REFERENCES tb_users(id) ON DELETE CASCADE,
    CONSTRAINT uq_email_notification_log UNIQUE (publication_id, user_id)
);
