CREATE TABLE tb_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(15) NOT NULL UNIQUE,
    email         VARCHAR(255) NOT NULL UNIQUE,
    name          VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP(6) NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_users_email    ON tb_users(email);
CREATE INDEX idx_users_username ON tb_users(username);

CREATE TABLE tb_user_roles (
    user_id BIGINT NOT NULL,
    role    VARCHAR(20) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES tb_users(id) ON DELETE CASCADE
);

CREATE TABLE tb_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE,
    filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size BIGINT NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    url VARCHAR(500) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_images_uuid ON tb_images(uuid);
CREATE INDEX idx_images_active ON tb_images(active);
CREATE INDEX idx_images_created_at ON tb_images(created_at);

CREATE TABLE tb_blogs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    slug        VARCHAR(255) NOT NULL,
    description TEXT,
    owner_id    BIGINT NOT NULL,
    main        BOOLEAN NOT NULL DEFAULT false,
    active      BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMP NOT NULL,
    git_enabled BOOLEAN NOT NULL DEFAULT false,
    git_remote_url VARCHAR(2048),
    git_branch VARCHAR(255) NOT NULL DEFAULT 'main',
    git_last_known_commit VARCHAR(64),

    CONSTRAINT pk_tb_blogs PRIMARY KEY (id),
    CONSTRAINT fk_blog_owner FOREIGN KEY (owner_id) REFERENCES tb_users(id),
    CONSTRAINT uq_blog_owner_slug UNIQUE (owner_id, slug)
);

INSERT INTO tb_users (username, email, name, password_hash, active) VALUES
                     ('admin', 'admin@contraponto.blog', 'Administrator', '$2a$10$9JdzFX8ar0ZcKP5bQkduBuwhFBRBgMW7.pCV4btIDcPgf.zdDGcCO', TRUE);

INSERT INTO tb_user_roles (user_id, role)
SELECT u.id, r.role
FROM tb_users u
CROSS JOIN (VALUES ('ADMIN'), ('USER_ADMINISTRATOR')) AS r(role)
WHERE u.username = 'admin';

INSERT INTO tb_blogs (name, slug, description, owner_id, main, active, created_at) VALUES
                    ('Administrator Blog', 'admin', 'Platform administration and announcements', (SELECT id FROM tb_users WHERE username = 'admin'), TRUE, TRUE, NOW());

CREATE TABLE tb_series (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blog_id    BIGINT NOT NULL,
    title      VARCHAR(255) NOT NULL,
    slug       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_series_blog FOREIGN KEY (blog_id) REFERENCES tb_blogs(id) ON DELETE CASCADE,
    CONSTRAINT uq_series_blog_slug UNIQUE (blog_id, slug)
);

CREATE INDEX idx_series_blog_id ON tb_series(blog_id);

CREATE TABLE tb_posts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug              VARCHAR(255) NOT NULL,
    blog_id           BIGINT NOT NULL,
    title             VARCHAR(255),
    cover_id          BIGINT,
    serie_id          BIGINT,
    description       VARCHAR(512) NOT NULL,
    content           TEXT NOT NULL,
    format            VARCHAR(20) NOT NULL,
    published         BOOLEAN NOT NULL DEFAULT FALSE,
    featured          BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP(6) NOT NULL,
    published_at      TIMESTAMP(6),
    updated_at        TIMESTAMP(6) NOT NULL,
    live_publication_id BIGINT,

    CONSTRAINT fk_posts_blog FOREIGN KEY (blog_id) REFERENCES tb_blogs(id),
    CONSTRAINT fk_posts_cover_image FOREIGN KEY (cover_id) REFERENCES tb_images(id),
    CONSTRAINT fk_posts_serie FOREIGN KEY (serie_id) REFERENCES tb_series(id) ON DELETE SET NULL,
    CONSTRAINT uk_posts_slug_user UNIQUE (slug, blog_id)
);

CREATE TABLE tb_tags (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        VARCHAR(255) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,

    CONSTRAINT uq_tags_slug UNIQUE (slug)
);

CREATE INDEX idx_tags_name_lower ON tb_tags (LOWER(name));

CREATE TABLE tb_post_tags (
    post_id BIGINT NOT NULL,
    tag_id  BIGINT NOT NULL,

    CONSTRAINT pk_post_tags PRIMARY KEY (post_id, tag_id),
    CONSTRAINT fk_post_tags_post FOREIGN KEY (post_id) REFERENCES tb_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_tags_tag FOREIGN KEY (tag_id) REFERENCES tb_tags(id) ON DELETE CASCADE
);

CREATE INDEX idx_post_tags_tag_id ON tb_post_tags(tag_id);

CREATE TABLE tb_post_publications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id         BIGINT NOT NULL,
    version         INT NOT NULL,
    published_at    TIMESTAMP(6) NOT NULL,
    slug            VARCHAR(255) NOT NULL,
    title           VARCHAR(255),
    description     VARCHAR(512) NOT NULL,
    content         TEXT NOT NULL,
    format          VARCHAR(20) NOT NULL,
    cover_id        BIGINT,

    CONSTRAINT fk_post_publications_post FOREIGN KEY (post_id) REFERENCES tb_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_publications_cover FOREIGN KEY (cover_id) REFERENCES tb_images(id),
    CONSTRAINT uq_post_publications_post_version UNIQUE (post_id, version)
);

CREATE INDEX idx_post_publications_post_id ON tb_post_publications(post_id);

CREATE TABLE tb_post_publication_tags (
    publication_id BIGINT NOT NULL,
    tag_id         BIGINT NOT NULL,

    CONSTRAINT pk_post_publication_tags PRIMARY KEY (publication_id, tag_id),
    CONSTRAINT fk_post_publication_tags_publication FOREIGN KEY (publication_id) REFERENCES tb_post_publications(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_publication_tags_tag FOREIGN KEY (tag_id) REFERENCES tb_tags(id) ON DELETE CASCADE
);

CREATE INDEX idx_post_publication_tags_tag_id ON tb_post_publication_tags(tag_id);

ALTER TABLE tb_posts
    ADD CONSTRAINT fk_posts_live_publication FOREIGN KEY (live_publication_id) REFERENCES tb_post_publications(id);

CREATE TABLE tb_custom_pages (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug              VARCHAR(255) NOT NULL,
    title             VARCHAR(255),
    section           VARCHAR(64),
    content           TEXT NOT NULL,
    placement         VARCHAR(20) NOT NULL,
    blog_id           BIGINT,
    published         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP(6) NOT NULL,
    published_at      TIMESTAMP(6),
    updated_at        TIMESTAMP(6) NOT NULL,

    CONSTRAINT fk_custom_pages_blog FOREIGN KEY (blog_id) REFERENCES tb_blogs(id),
    CONSTRAINT uk_custom_pages_slug UNIQUE (slug, blog_id)
);

CREATE TABLE tb_views (
    id BIGSERIAL PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES tb_posts(id) ON DELETE CASCADE,
    user_id BIGINT,
    session_id VARCHAR(255) NOT NULL,
    viewed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_views_user FOREIGN KEY (user_id) REFERENCES tb_users(id),
    CONSTRAINT fk_views_post FOREIGN KEY (post_id) REFERENCES tb_posts(id)
);

CREATE TABLE tb_blog_audience (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    blog_id          BIGINT NOT NULL,
    followed         BOOLEAN NOT NULL DEFAULT FALSE,
    email_subscribed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_blog_audience_user FOREIGN KEY (user_id) REFERENCES tb_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_blog_audience_blog FOREIGN KEY (blog_id) REFERENCES tb_blogs(id) ON DELETE CASCADE,
    CONSTRAINT uq_blog_audience_user_blog UNIQUE (user_id, blog_id),
    CONSTRAINT chk_blog_audience_active CHECK (followed OR email_subscribed)
);

CREATE INDEX idx_blog_audience_blog_followed ON tb_blog_audience(blog_id) WHERE followed = TRUE;
CREATE INDEX idx_blog_audience_blog_email ON tb_blog_audience(blog_id) WHERE email_subscribed = TRUE;

CREATE TABLE tb_notifications (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id  BIGINT NOT NULL,
    type               VARCHAR(32) NOT NULL,
    blog_id            BIGINT NOT NULL,
    post_id            BIGINT,
    publication_id     BIGINT,
    actor_user_id      BIGINT,
    read               BOOLEAN NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_user_id) REFERENCES tb_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_blog FOREIGN KEY (blog_id) REFERENCES tb_blogs(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_post FOREIGN KEY (post_id) REFERENCES tb_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_publication FOREIGN KEY (publication_id) REFERENCES tb_post_publications(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_actor FOREIGN KEY (actor_user_id) REFERENCES tb_users(id) ON DELETE SET NULL
);

CREATE INDEX idx_notifications_recipient_read_created ON tb_notifications(recipient_user_id, read, created_at DESC);

CREATE TABLE tb_post_comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT NOT NULL,
    author_id   BIGINT NOT NULL,
    parent_id   BIGINT,
    root_id     BIGINT,
    body        TEXT NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at  TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    approved_at TIMESTAMP(6),

    CONSTRAINT fk_post_comments_post FOREIGN KEY (post_id) REFERENCES tb_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_comments_author FOREIGN KEY (author_id) REFERENCES tb_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_comments_parent FOREIGN KEY (parent_id) REFERENCES tb_post_comments(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_comments_root FOREIGN KEY (root_id) REFERENCES tb_post_comments(id) ON DELETE CASCADE,
    CONSTRAINT chk_post_comments_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX idx_post_comments_post_roots ON tb_post_comments(post_id) WHERE parent_id IS NULL;
CREATE INDEX idx_post_comments_root_status ON tb_post_comments(root_id, status);
CREATE INDEX idx_post_comments_post_status ON tb_post_comments(post_id, status);

ALTER TABLE tb_notifications ADD COLUMN comment_id BIGINT;
ALTER TABLE tb_notifications ADD CONSTRAINT fk_notifications_comment
    FOREIGN KEY (comment_id) REFERENCES tb_post_comments(id) ON DELETE CASCADE;

CREATE TABLE tb_email_notification_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id  BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    sent_at         TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_email_notification_log_publication FOREIGN KEY (publication_id) REFERENCES tb_post_publications(id) ON DELETE CASCADE,
    CONSTRAINT fk_email_notification_log_user FOREIGN KEY (user_id) REFERENCES tb_users(id) ON DELETE CASCADE,
    CONSTRAINT uq_email_notification_log UNIQUE (publication_id, user_id)
);

DELETE FROM tb_custom_pages WHERE slug IN ('/sobre', '/contato', '/privacidade', '/termos');

INSERT INTO tb_custom_pages (slug, section, title, content, placement, published, created_at, published_at, updated_at) VALUES
(
    '/sobre',
    'Explore',
    'Sobre o Contraponto',
    '<h2>Bem-vindo ao Contraponto</h2>
    <p>O <strong>Contraponto</strong> é um espaço para ideias, críticas e narrativas que desafiam o senso comum.
    Acreditamos que toda história tem mais de um lado, e nosso objetivo é trazer perspectivas diversas sobre
    literatura, tecnologia, política e cultura.</p>
    <h3>Nossa missão</h3>
    <p>Oferecer conteúdo independente e de qualidade, estimulando o pensamento crítico e o debate respeitoso.</p>
    <h3>Quem escreve</h3>
    <p>Somos uma comunidade de escritores, programadores, professores e curiosos.
    Se você tem algo a dizer, <a href="/contato">entre em contato</a> e faça parte do time.</p>
    <p><em>“A verdade é raramente pura e nunca simples.” – Oscar Wilde</em></p>',
    'FOOTER',
    TRUE,
    NOW(),
    NOW(),
    NOW()
),
(
    '/contato',
    'Connect',
    'Contato',
    '<h2>Fale conosco</h2>
    <p>Tem alguma sugestão, crítica ou quer contribuir com o blog? Adoraríamos ouvir você!</p>
    <p><strong>E-mail:</strong> <a href="mailto:contato@contraponto.blog">contato@contraponto.blog</a></p>
    <p><strong>Redes sociais:</strong></p>
    <ul>
        <li>Twitter: <a href="#">@contraponto_blog</a></li>
        <li>Mastodon: <a href="#">@contraponto@social.blog</a></li>
    </ul>
    <p>Responderemos em até 48 horas úteis.</p>',
    'FOOTER',
    TRUE,
    NOW(),
    NOW(),
    NOW()
),
(
    '/privacidade',
    'Legal',
    'Política de Privacidade',
    '<h2>Política de Privacidade do Contraponto</h2>
    <p>A sua privacidade é importante para nós. Esta política explica quais dados coletamos, como os usamos e
    quais direitos você tem.</p>
    <h3>Dados coletados</h3>
    <ul>
        <li><strong>Cadastro:</strong> nome, e-mail, nome de usuário.</li>
        <li><strong>Uso:</strong> visualizações de posts, tempo de sessão, endereço IP anonimizado.</li>
        <li><strong>Cookies:</strong> utilizamos cookies de sessão para autenticação e preferências.</li>
    </ul>
    <h3>Como usamos seus dados</h3>
    <p>Os dados são usados exclusivamente para operar o blog, melhorar a experiência do usuário e enviar
    notificações (se você optar por recebê-las). Nunca vendemos ou compartilhamos seus dados com terceiros
    sem seu consentimento explícito.</p>
    <p>Para dúvidas: <strong>privacidade@contraponto.blog</strong>.</p>
    <p><em>Última atualização: maio de 2026</em></p>',
    'FOOTER',
    TRUE,
    NOW(),
    NOW(),
    NOW()
),
(
    '/termos',
    'Legal',
    'Termos de Uso',
    '<h2>Termos de Uso do Contraponto</h2>
    <p>Ao acessar ou utilizar o Contraponto, você concorda com os seguintes termos:</p>
    <h3>Conteúdo</h3>
    <p>Todo o conteúdo publicado no blog é de responsabilidade dos autores. As opiniões expressas não refletem
    necessariamente a posição da plataforma.</p>
    <h3>Comentários e interações</h3>
    <p>Respeite outros usuários. Não são permitidos discursos de ódio, assédio, spam ou conteúdo ilegal.</p>
    <h3>Propriedade intelectual</h3>
    <p>Os textos permanecem sob propriedade dos autores, com licença não exclusiva para exibição na plataforma.</p>',
    'FOOTER',
    TRUE,
    NOW(),
    NOW(),
    NOW()
);
